name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/issue.yml'
      - '.github/workflows/pull_request.yml'
      - 'fastlane/**'
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # =============== 新增步骤 ===============
      # 这个步骤会自动创建 local.properties 并写入 SDK 路径
      - name: Create local.properties
        run: |
          echo "sdk.dir=${ANDROID_HOME}" >> local.properties
          echo "officialBuild=true" >> local.properties
      # ======================================

      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Gradle prebuild
        run: |
          ./gradlew prebuild

      - name: Build all
        id: buildAll
        run: |
          ./gradlew assemble
          echo "releaseName=$(ls app/build/outputs/apk/release/*.apk | awk -F '(/|.apk)' '{print $6}')" >> $GITHUB_OUTPUT
          echo "debugName=$(ls app/build/outputs/apk/debug/*.apk | awk -F '(/|.apk)' '{print $6}')" >> $GITHUB_OUTPUT

      - name: Upload Release APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.buildAll.outputs.releaseName }}
          path: app/build/outputs/apk/release/*.apk

      - name: Upload Debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.buildAll.outputs.debugName }}
          path: app/build/outputs/apk/debug/*.apk
